// generated by CommonLibrary.cmake, do not edit.

/**
 * @file include/lava/version.h
 * Defines version macros and class for library lava.
 */

#ifndef LAVA_VERSION_H
#define LAVA_VERSION_H

#include "api.h"
#include <string>

namespace lava
{
    /** The current major version. */
#   define LAVA_VERSION_MAJOR 2

    /** The current minor version. */
#   define LAVA_VERSION_MINOR 1

    /** The current patch level. */
#   define LAVA_VERSION_PATCH 0

    /** The current SCM revision. */
#   define LAVA_VERSION_REVISION 0xa8ce751

    /** The current binary interface. */
#   define LAVA_VERSION_ABI 3ull

/** True if the current version is newer than the given one. */
#   define LAVA_VERSION_GT( MAJOR, MINOR, PATCH )       \
    ( (LAVA_VERSION_MAJOR>MAJOR) ||                     \
      (LAVA_VERSION_MAJOR==MAJOR && (LAVA_VERSION_MINOR>MINOR || \
          (LAVA_VERSION_MINOR==MINOR && LAVA_VERSION_PATCH>PATCH))))

/** True if the current version is equal or newer to the given. */
#   define LAVA_VERSION_GE( MAJOR, MINOR, PATCH )       \
    ( (LAVA_VERSION_MAJOR>MAJOR) ||                     \
      (LAVA_VERSION_MAJOR==MAJOR && (LAVA_VERSION_MINOR>MINOR || \
          (LAVA_VERSION_MINOR==MINOR && LAVA_VERSION_PATCH>=PATCH))))

/** True if the current version is older than the given one. */
#   define LAVA_VERSION_LT( MAJOR, MINOR, PATCH )       \
    ( (LAVA_VERSION_MAJOR<MAJOR) ||                     \
      (LAVA_VERSION_MAJOR==MAJOR && (LAVA_VERSION_MINOR<MINOR || \
          (LAVA_VERSION_MINOR==MINOR && LAVA_VERSION_PATCH<PATCH))))

/** True if the current version is older or equal to the given. */
#   define LAVA_VERSION_LE( MAJOR, MINOR, PATCH )       \
    ( (LAVA_VERSION_MAJOR<MAJOR) ||                     \
      (LAVA_VERSION_MAJOR==MAJOR && (LAVA_VERSION_MINOR<MINOR || \
        (LAVA_VERSION_MINOR==MINOR && LAVA_VERSION_PATCH<=PATCH))))

/** Information about the current lava version. */
class LAVA_API Version
{
public:
    /** @return the current major version of lava. */
    static int getMajor();

    /** @return the current minor version of lava. */
    static int getMinor();

    /** @return the current patch level of lava. */
    static int getPatch();

    /** @return the current lava version (MM.mm.pp). */
    static std::string getString();

    /** @return the SCM revision. */
    static unsigned long long getRevision();

    /** @return the current binary interface version of lava. */
    static int getABI();

    /** @return the current lava version plus the git SHA hash (MM.mm.pp.rev). */
    static std::string getRevString();

    /**
     * Runtime check for ABI compatibility.
     *
     * Call from code using lava. Will fail if the executable
     * was compiled against a version incompatible with the runtime version.
     *
     * @return true if the link-time and compile-time DSO are compatible.
     */
    static bool check()
    {
        return getMajor()==LAVA_VERSION_MAJOR &&
               getMinor()==LAVA_VERSION_MINOR;
    }

    /** @return JSON schema describing this object. */
    static std::string getSchema()
    {
        return R"(
                {
                  "title": "Version",
                  "type": "object",
                  "description": "Version information of the running application",
                  "properties": {
                    "major": { "type": "integer" },
                    "minor": { "type": "integer" },
                    "patch": { "type": "integer" },
                    "abi": { "type": "integer" },
                    "revision": { "type": "string" }
                  }
               }
               )";
    }

    /** @return JSON-encoded data for this object. */
    static std::string toJSON()
    {
        return R"(
               {
                 "major": 2,
                 "minor": 1,
                 "patch": 0,
                 "abi": 3,
                 "revision": "a8ce751"
               }
               )";
    }
};

}

#endif
